# Generated by Django 4.2 on 2024-02-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_notes', to='notes.user'),
        ),
        migrations.AddField(
            model_name='note',
            name='versions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
